name: code_block
description: CodeBlock Component that provides a rich code block using AppFlowy Editor.
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  appflowy_editor: ^1.3.0
  flutter:
    sdk: flutter
  highlight: ^0.7.0
  flutter_localizations:
    sdk: flutter
  rich_clipboard: ^1.0.0
  intl_utils: ^2.8.2
  intl: ^0.18.0
  markdown: ^7.1.0
  file_picker: ^5.3.1
  path: ^1.8.3  
  appflowy_popover:
    path: packages/appflowy_popover
  flowy_infra_ui:
    path: packages/flowy_infra_ui
  flowy_infra:
    path: packages/flowy_infra
  font_awesome_flutter: ^10.5.0
      
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockingjay: ^0.3.0
  mocktail: ^0.3.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
